# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Publish

on:
  push:
    branches:
      - master
    tags:
      - '*' # run on all tags being pushed

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtimeIdentifier:
          [
            win-x64,
            win-x86,
            linux-x64,
            linux-arm,
            linux-arm64,
            osx-x64,
            osx-arm64,
            linux-musl-x64,
            linux-musl-arm,
            linux-musl-arm64,
          ]

    steps:
    - uses: actions/checkout@v4
      with: 
        fetch-depth: 0
        submodules: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.0.1
      with:
        versionSpec: '6.0.5'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      shell: bash
      run: dotnet publish --no-self-contained -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:DebugType=none -p:RuntimeIdentifier=${{ matrix.runtimeIdentifier }} --framework net9.0
    - name: Upload binary files(${{ matrix.runtimeIdentifier }}) for .NET 9.0
      uses: actions/upload-artifact@v4
      with:
        name: LyainBot_${{ matrix.runtimeIdentifier }}_net9.0_NoSelfContained
        path: LyainBot/bin/Release/net9.0/${{ matrix.runtimeIdentifier }}/publish
  release:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Make artifacts directory
      run: mkdir artifacts
    - name: Download all binary files
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    - name: Zip all binary files pre directory
      run: |
        cd artifacts
        for d in */; do zip -r "${d%/}.zip" "$d"; done
    - name: Create release
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/*.zip
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ github.ref }}
        draft: false
        prerelease: false
        generate_release_notes: true
    - name: Remove latest release
      if: ${{ contains(github.ref, 'master') }}
      run: |
        latest_release=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/LyainTeam/LyainBot/releases/tags/latest)
        release_id=$(echo "$latest_release" | jq -r '.id')
        curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/LyainTeam/LyainBot/releases/$release_id
    - name: Create pre-release
      if: ${{ contains(github.ref, 'master') }}
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/*.zip
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: latest
        draft: false
        prerelease: true
        generate_release_notes: true